// Code generated by protoc-gen-go. DO NOT EDIT.
// source: apollo/apollo.proto

/*
Package apollo is a generated protocol buffer package.

It is generated from these files:
	apollo/apollo.proto

It has these top-level messages:
	OptExtras
	AuthOpt
	AuthResp
	GetReq
	GetResp
	ACL
*/
package apollo

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import celestial "github.com/c12s/scheme/celestial"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type OptExtras struct {
	Data []string `protobuf:"bytes,1,rep,name=data" json:"data,omitempty"`
}

func (m *OptExtras) Reset()                    { *m = OptExtras{} }
func (m *OptExtras) String() string            { return proto.CompactTextString(m) }
func (*OptExtras) ProtoMessage()               {}
func (*OptExtras) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *OptExtras) GetData() []string {
	if m != nil {
		return m.Data
	}
	return nil
}

type AuthOpt struct {
	Data   map[string]string     `protobuf:"bytes,1,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Extras map[string]*OptExtras `protobuf:"bytes,2,rep,name=extras" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AuthOpt) Reset()                    { *m = AuthOpt{} }
func (m *AuthOpt) String() string            { return proto.CompactTextString(m) }
func (*AuthOpt) ProtoMessage()               {}
func (*AuthOpt) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *AuthOpt) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *AuthOpt) GetExtras() map[string]*OptExtras {
	if m != nil {
		return m.Extras
	}
	return nil
}

type AuthResp struct {
	Value bool              `protobuf:"varint,1,opt,name=value" json:"value,omitempty"`
	Data  map[string]string `protobuf:"bytes,2,rep,name=data" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *AuthResp) Reset()                    { *m = AuthResp{} }
func (m *AuthResp) String() string            { return proto.CompactTextString(m) }
func (*AuthResp) ProtoMessage()               {}
func (*AuthResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *AuthResp) GetValue() bool {
	if m != nil {
		return m.Value
	}
	return false
}

func (m *AuthResp) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type GetReq struct {
	User string `protobuf:"bytes,1,opt,name=user" json:"user,omitempty"`
}

func (m *GetReq) Reset()                    { *m = GetReq{} }
func (m *GetReq) String() string            { return proto.CompactTextString(m) }
func (*GetReq) ProtoMessage()               {}
func (*GetReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *GetReq) GetUser() string {
	if m != nil {
		return m.User
	}
	return ""
}

type GetResp struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *GetResp) Reset()                    { *m = GetResp{} }
func (m *GetResp) String() string            { return proto.CompactTextString(m) }
func (*GetResp) ProtoMessage()               {}
func (*GetResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *GetResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ACL struct {
	Token []string `protobuf:"bytes,1,rep,name=token" json:"token,omitempty"`
}

func (m *ACL) Reset()                    { *m = ACL{} }
func (m *ACL) String() string            { return proto.CompactTextString(m) }
func (*ACL) ProtoMessage()               {}
func (*ACL) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ACL) GetToken() []string {
	if m != nil {
		return m.Token
	}
	return nil
}

func init() {
	proto.RegisterType((*OptExtras)(nil), "apollo.OptExtras")
	proto.RegisterType((*AuthOpt)(nil), "apollo.AuthOpt")
	proto.RegisterType((*AuthResp)(nil), "apollo.AuthResp")
	proto.RegisterType((*GetReq)(nil), "apollo.GetReq")
	proto.RegisterType((*GetResp)(nil), "apollo.GetResp")
	proto.RegisterType((*ACL)(nil), "apollo.ACL")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for ApolloService service

type ApolloServiceClient interface {
	GetToken(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error)
	Auth(ctx context.Context, in *AuthOpt, opts ...grpc.CallOption) (*AuthResp, error)
	List(ctx context.Context, in *celestial.ListReq, opts ...grpc.CallOption) (*celestial.ListResp, error)
	Mutate(ctx context.Context, in *celestial.MutateReq, opts ...grpc.CallOption) (*celestial.MutateResp, error)
}

type apolloServiceClient struct {
	cc *grpc.ClientConn
}

func NewApolloServiceClient(cc *grpc.ClientConn) ApolloServiceClient {
	return &apolloServiceClient{cc}
}

func (c *apolloServiceClient) GetToken(ctx context.Context, in *GetReq, opts ...grpc.CallOption) (*GetResp, error) {
	out := new(GetResp)
	err := grpc.Invoke(ctx, "/apollo.ApolloService/GetToken", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apolloServiceClient) Auth(ctx context.Context, in *AuthOpt, opts ...grpc.CallOption) (*AuthResp, error) {
	out := new(AuthResp)
	err := grpc.Invoke(ctx, "/apollo.ApolloService/Auth", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apolloServiceClient) List(ctx context.Context, in *celestial.ListReq, opts ...grpc.CallOption) (*celestial.ListResp, error) {
	out := new(celestial.ListResp)
	err := grpc.Invoke(ctx, "/apollo.ApolloService/List", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *apolloServiceClient) Mutate(ctx context.Context, in *celestial.MutateReq, opts ...grpc.CallOption) (*celestial.MutateResp, error) {
	out := new(celestial.MutateResp)
	err := grpc.Invoke(ctx, "/apollo.ApolloService/Mutate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for ApolloService service

type ApolloServiceServer interface {
	GetToken(context.Context, *GetReq) (*GetResp, error)
	Auth(context.Context, *AuthOpt) (*AuthResp, error)
	List(context.Context, *celestial.ListReq) (*celestial.ListResp, error)
	Mutate(context.Context, *celestial.MutateReq) (*celestial.MutateResp, error)
}

func RegisterApolloServiceServer(s *grpc.Server, srv ApolloServiceServer) {
	s.RegisterService(&_ApolloService_serviceDesc, srv)
}

func _ApolloService_GetToken_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApolloServiceServer).GetToken(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apollo.ApolloService/GetToken",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApolloServiceServer).GetToken(ctx, req.(*GetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApolloService_Auth_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthOpt)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApolloServiceServer).Auth(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apollo.ApolloService/Auth",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApolloServiceServer).Auth(ctx, req.(*AuthOpt))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApolloService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(celestial.ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApolloServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apollo.ApolloService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApolloServiceServer).List(ctx, req.(*celestial.ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _ApolloService_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(celestial.MutateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ApolloServiceServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/apollo.ApolloService/Mutate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ApolloServiceServer).Mutate(ctx, req.(*celestial.MutateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _ApolloService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "apollo.ApolloService",
	HandlerType: (*ApolloServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetToken",
			Handler:    _ApolloService_GetToken_Handler,
		},
		{
			MethodName: "Auth",
			Handler:    _ApolloService_Auth_Handler,
		},
		{
			MethodName: "List",
			Handler:    _ApolloService_List_Handler,
		},
		{
			MethodName: "Mutate",
			Handler:    _ApolloService_Mutate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "apollo/apollo.proto",
}

func init() { proto.RegisterFile("apollo/apollo.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 412 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x53, 0xdd, 0x4e, 0xd4, 0x50,
	0x10, 0xa6, 0xbb, 0x6b, 0xd9, 0xce, 0x46, 0xc1, 0x01, 0x93, 0x52, 0x34, 0x4b, 0xce, 0x8d, 0x24,
	0x86, 0x36, 0x94, 0x0b, 0x8c, 0x77, 0xab, 0x12, 0x6e, 0xd6, 0x90, 0x54, 0xaf, 0xbc, 0x3b, 0xd4,
	0x89, 0xdb, 0x50, 0x68, 0xed, 0x99, 0x12, 0x79, 0x04, 0x9f, 0xd0, 0x17, 0xf1, 0x01, 0xcc, 0xf9,
	0xa1, 0xd4, 0xba, 0x57, 0x5c, 0x75, 0x66, 0xbe, 0xf9, 0xbe, 0x99, 0xef, 0x9c, 0x1e, 0xd8, 0x91,
	0x75, 0x55, 0x96, 0x55, 0x62, 0x3f, 0x71, 0xdd, 0x54, 0x5c, 0xa1, 0x6f, 0xb3, 0x68, 0x2f, 0xa7,
	0x92, 0x14, 0x17, 0xb2, 0x4c, 0xba, 0xc8, 0xb6, 0x88, 0x39, 0x04, 0x17, 0x35, 0x9f, 0xfd, 0xe4,
	0x46, 0x2a, 0x44, 0x98, 0x7c, 0x93, 0x2c, 0x43, 0xef, 0x60, 0x7c, 0x18, 0x64, 0x26, 0x16, 0x7f,
	0x3c, 0xd8, 0x5c, 0xb4, 0xbc, 0xba, 0xa8, 0x19, 0x8f, 0x7a, 0xf8, 0x2c, 0xdd, 0x8b, 0xdd, 0x30,
	0x07, 0xc7, 0x1f, 0x25, 0xcb, 0xb3, 0x1b, 0x6e, 0xee, 0x2c, 0x15, 0x4f, 0xc0, 0x27, 0x23, 0x1c,
	0x8e, 0x0c, 0x61, 0x7f, 0x48, 0xb0, 0x63, 0x2d, 0xc5, 0xb5, 0x46, 0xa7, 0x10, 0x74, 0x3a, 0xb8,
	0x0d, 0xe3, 0x2b, 0xba, 0x0b, 0xbd, 0x03, 0xef, 0x30, 0xc8, 0x74, 0x88, 0xbb, 0xf0, 0xe4, 0x56,
	0x96, 0x2d, 0x85, 0x23, 0x53, 0xb3, 0xc9, 0xbb, 0xd1, 0x5b, 0x2f, 0x5a, 0xc2, 0xac, 0xa7, 0xb7,
	0x86, 0xfa, 0xba, 0x4f, 0x9d, 0xa5, 0xcf, 0xef, 0xb7, 0xe9, 0xfc, 0xf7, 0xd4, 0xc4, 0x2f, 0x0f,
	0xa6, 0x7a, 0xcd, 0x8c, 0x54, 0xfd, 0x30, 0x54, 0xab, 0x4d, 0x5d, 0x1b, 0xc6, 0xee, 0x34, 0xac,
	0xb9, 0xa8, 0x6f, 0x4e, 0xb3, 0x86, 0xc7, 0xf1, 0x68, 0x67, 0xe2, 0x25, 0xf8, 0xe7, 0xc4, 0x19,
	0xfd, 0xd0, 0x17, 0xd4, 0x2a, 0x6a, 0x1c, 0xcd, 0xc4, 0x62, 0x0e, 0x9b, 0x06, 0xb5, 0x7b, 0x72,
	0x75, 0x45, 0x37, 0x0e, 0xb7, 0x89, 0xd8, 0x87, 0xf1, 0xe2, 0xc3, 0xb2, 0x0f, 0x8e, 0x3b, 0x30,
	0xfd, 0xed, 0xc1, 0xd3, 0x85, 0x59, 0xfc, 0x33, 0x35, 0xb7, 0x45, 0x4e, 0x78, 0x04, 0xd3, 0x73,
	0xe2, 0x2f, 0x1a, 0xc5, 0x67, 0xf7, 0xa6, 0xec, 0xfc, 0x68, 0xeb, 0x9f, 0x5c, 0xd5, 0x62, 0x03,
	0xdf, 0xc0, 0x44, 0x3b, 0xc6, 0xad, 0xc1, 0xe5, 0x46, 0xdb, 0xc3, 0x03, 0x11, 0x1b, 0x78, 0x0c,
	0x93, 0x65, 0xa1, 0x18, 0x31, 0x7e, 0xf8, 0x0f, 0x75, 0x41, 0x6b, 0xef, 0xfc, 0x57, 0x33, 0x94,
	0x53, 0xf0, 0x3f, 0xb5, 0x2c, 0x99, 0x70, 0xb7, 0xd7, 0x60, 0x4b, 0x9a, 0xf6, 0x62, 0x4d, 0x55,
	0x13, 0xdf, 0xcf, 0xbf, 0xbe, 0xfa, 0x5e, 0xf0, 0xaa, 0xbd, 0x8c, 0xf3, 0xea, 0x3a, 0xc9, 0x8f,
	0x53, 0x95, 0xa8, 0x7c, 0x45, 0xd7, 0xe4, 0xde, 0xc8, 0xa5, 0x6f, 0x5e, 0xc0, 0xc9, 0xdf, 0x00,
	0x00, 0x00, 0xff, 0xff, 0x3e, 0xed, 0xdd, 0x88, 0x3b, 0x03, 0x00, 0x00,
}
