// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gravity/gravity.proto

/*
Package gravity is a generated protocol buffer package.

It is generated from these files:
	gravity/gravity.proto

It has these top-level messages:
	PutReq
	PutResp
	FlushTaskPart
	FlushTask
*/
package gravity

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import celestial "github.com/c12s/scheme/celestial"
import blackhole "github.com/c12s/scheme/blackhole"
import stellar "github.com/c12s/scheme/stellar"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PutReq struct {
	Key     string               `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Task    *celestial.MutateReq `protobuf:"bytes,2,opt,name=task" json:"task,omitempty"`
	TaskKey string               `protobuf:"bytes,3,opt,name=taskKey" json:"taskKey,omitempty"`
}

func (m *PutReq) Reset()                    { *m = PutReq{} }
func (m *PutReq) String() string            { return proto.CompactTextString(m) }
func (*PutReq) ProtoMessage()               {}
func (*PutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *PutReq) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *PutReq) GetTask() *celestial.MutateReq {
	if m != nil {
		return m.Task
	}
	return nil
}

func (m *PutReq) GetTaskKey() string {
	if m != nil {
		return m.TaskKey
	}
	return ""
}

type PutResp struct {
	Token string `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
}

func (m *PutResp) Reset()                    { *m = PutResp{} }
func (m *PutResp) String() string            { return proto.CompactTextString(m) }
func (*PutResp) ProtoMessage()               {}
func (*PutResp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *PutResp) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type FlushTaskPart struct {
	Nodes []string `protobuf:"bytes,1,rep,name=nodes" json:"nodes,omitempty"`
}

func (m *FlushTaskPart) Reset()                    { *m = FlushTaskPart{} }
func (m *FlushTaskPart) String() string            { return proto.CompactTextString(m) }
func (*FlushTaskPart) ProtoMessage()               {}
func (*FlushTaskPart) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *FlushTaskPart) GetNodes() []string {
	if m != nil {
		return m.Nodes
	}
	return nil
}

type FlushTask struct {
	Parts       []*FlushTaskPart     `protobuf:"bytes,1,rep,name=parts" json:"parts,omitempty"`
	Payload     []*blackhole.Payload `protobuf:"bytes,2,rep,name=payload" json:"payload,omitempty"`
	Strategy    *blackhole.Strategy  `protobuf:"bytes,3,opt,name=strategy" json:"strategy,omitempty"`
	TaskKey     string               `protobuf:"bytes,4,opt,name=taskKey" json:"taskKey,omitempty"`
	SpanContext *stellar.SpanContext `protobuf:"bytes,5,opt,name=spanContext" json:"spanContext,omitempty"`
}

func (m *FlushTask) Reset()                    { *m = FlushTask{} }
func (m *FlushTask) String() string            { return proto.CompactTextString(m) }
func (*FlushTask) ProtoMessage()               {}
func (*FlushTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *FlushTask) GetParts() []*FlushTaskPart {
	if m != nil {
		return m.Parts
	}
	return nil
}

func (m *FlushTask) GetPayload() []*blackhole.Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

func (m *FlushTask) GetStrategy() *blackhole.Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func (m *FlushTask) GetTaskKey() string {
	if m != nil {
		return m.TaskKey
	}
	return ""
}

func (m *FlushTask) GetSpanContext() *stellar.SpanContext {
	if m != nil {
		return m.SpanContext
	}
	return nil
}

func init() {
	proto.RegisterType((*PutReq)(nil), "gravity.PutReq")
	proto.RegisterType((*PutResp)(nil), "gravity.PutResp")
	proto.RegisterType((*FlushTaskPart)(nil), "gravity.FlushTaskPart")
	proto.RegisterType((*FlushTask)(nil), "gravity.FlushTask")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for GravityService service

type GravityServiceClient interface {
	PutTask(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*PutResp, error)
}

type gravityServiceClient struct {
	cc *grpc.ClientConn
}

func NewGravityServiceClient(cc *grpc.ClientConn) GravityServiceClient {
	return &gravityServiceClient{cc}
}

func (c *gravityServiceClient) PutTask(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*PutResp, error) {
	out := new(PutResp)
	err := grpc.Invoke(ctx, "/gravity.GravityService/PutTask", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for GravityService service

type GravityServiceServer interface {
	PutTask(context.Context, *PutReq) (*PutResp, error)
}

func RegisterGravityServiceServer(s *grpc.Server, srv GravityServiceServer) {
	s.RegisterService(&_GravityService_serviceDesc, srv)
}

func _GravityService_PutTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GravityServiceServer).PutTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/gravity.GravityService/PutTask",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GravityServiceServer).PutTask(ctx, req.(*PutReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _GravityService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "gravity.GravityService",
	HandlerType: (*GravityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "PutTask",
			Handler:    _GravityService_PutTask_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "gravity/gravity.proto",
}

func init() { proto.RegisterFile("gravity/gravity.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 368 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x92, 0x4f, 0xab, 0x9b, 0x40,
	0x14, 0xc5, 0x6b, 0xfe, 0xd9, 0x8c, 0xb4, 0x0d, 0xd3, 0xa4, 0x98, 0x2c, 0x5a, 0x11, 0x0a, 0x59,
	0x04, 0xa5, 0x16, 0xba, 0x2e, 0x2d, 0xb4, 0x8b, 0x52, 0x08, 0x93, 0xb7, 0x7a, 0x8b, 0x07, 0x13,
	0x73, 0x89, 0xe2, 0xc4, 0x31, 0xce, 0x35, 0x3c, 0xbf, 0xf2, 0xfb, 0x14, 0x0f, 0x67, 0xd4, 0x24,
	0xab, 0x7b, 0xef, 0x9c, 0x9f, 0x33, 0x9c, 0x73, 0x25, 0x8b, 0x63, 0xc9, 0x2f, 0x29, 0xd6, 0x61,
	0x5b, 0x83, 0xa2, 0x94, 0x28, 0xa9, 0xdd, 0x8e, 0xab, 0x65, 0x0c, 0x02, 0x14, 0xa6, 0x5c, 0x84,
	0x7d, 0x67, 0x98, 0xd5, 0x72, 0x2f, 0x78, 0x9c, 0x25, 0x52, 0x40, 0xd8, 0x77, 0xad, 0xb4, 0x50,
	0x08, 0x42, 0xf0, 0x32, 0x6c, 0xab, 0x39, 0xf6, 0x9f, 0xc8, 0x64, 0x5b, 0x21, 0x83, 0x33, 0x9d,
	0x91, 0x61, 0x06, 0xb5, 0x6b, 0x79, 0xd6, 0x7a, 0xca, 0x9a, 0x96, 0xae, 0xc9, 0x08, 0xb9, 0xca,
	0xdc, 0x81, 0x67, 0xad, 0x9d, 0x68, 0x1e, 0x5c, 0x5f, 0xfb, 0x5f, 0x21, 0x47, 0x60, 0x70, 0x66,
	0x9a, 0xa0, 0x2e, 0xb1, 0x9b, 0xfa, 0x0f, 0x6a, 0x77, 0xa8, 0xbf, 0xef, 0x46, 0xff, 0x0b, 0xb1,
	0xf5, 0xfd, 0xaa, 0xa0, 0x73, 0x32, 0x46, 0x99, 0x41, 0xde, 0x3e, 0x61, 0x06, 0xff, 0x2b, 0x79,
	0xf7, 0x47, 0x54, 0x2a, 0x79, 0xe0, 0x2a, 0xdb, 0xf2, 0x12, 0x1b, 0x2c, 0x97, 0x07, 0x50, 0xae,
	0xe5, 0x0d, 0x1b, 0x4c, 0x0f, 0xfe, 0x8b, 0x45, 0xa6, 0x3d, 0x47, 0x37, 0x64, 0x5c, 0xf0, 0x12,
	0x0d, 0xe3, 0x44, 0x9f, 0x82, 0x2e, 0xaa, 0xbb, 0xab, 0x98, 0x81, 0xe8, 0x86, 0xd8, 0x05, 0xaf,
	0x85, 0xe4, 0x07, 0x77, 0xa0, 0x79, 0x1a, 0x5c, 0xd3, 0xd9, 0x1a, 0x85, 0x75, 0x08, 0x0d, 0xc9,
	0x5b, 0x85, 0x25, 0x47, 0x38, 0x1a, 0x33, 0x4e, 0xf4, 0xf1, 0x06, 0xdf, 0xb5, 0x12, 0xeb, 0xa1,
	0x5b, 0xf3, 0xa3, 0x3b, 0xf3, 0xf4, 0x07, 0x71, 0x54, 0xc1, 0xf3, 0xdf, 0x32, 0x47, 0x78, 0x46,
	0x77, 0xdc, 0xe6, 0xd8, 0x6d, 0x60, 0x77, 0xd5, 0xd8, 0x2d, 0x18, 0xfd, 0x24, 0xef, 0xff, 0x1a,
	0x43, 0x3b, 0x28, 0x2f, 0x69, 0x0c, 0x34, 0xd0, 0x31, 0x6a, 0xef, 0x1f, 0x7a, 0xb3, 0x66, 0x71,
	0xab, 0xd9, 0xfd, 0x81, 0x2a, 0xfc, 0x37, 0xbf, 0xbc, 0xc7, 0xcf, 0xc7, 0x14, 0x93, 0x6a, 0x1f,
	0xc4, 0xf2, 0x14, 0xc6, 0xdf, 0x22, 0x15, 0xaa, 0x38, 0x81, 0x13, 0x74, 0x3f, 0xd5, 0x7e, 0xa2,
	0xf7, 0xff, 0xfd, 0x35, 0x00, 0x00, 0xff, 0xff, 0xd4, 0x43, 0x27, 0x14, 0x6e, 0x02, 0x00, 0x00,
}
