// Code generated by protoc-gen-go. DO NOT EDIT.
// source: blackhole/blackhole.proto

/*
Package blackhole is a generated protocol buffer package.

It is generated from these files:
	blackhole/blackhole.proto

It has these top-level messages:
	Strategy
	Selector
	Payload
	Metadata
	PutTask
	PutReq
	Resp
*/
package blackhole

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

// Enums
type TaskKind int32

const (
	TaskKind_CONFIGS    TaskKind = 0
	TaskKind_ACTIONS    TaskKind = 1
	TaskKind_SECRETS    TaskKind = 2
	TaskKind_NAMESPACES TaskKind = 3
)

var TaskKind_name = map[int32]string{
	0: "CONFIGS",
	1: "ACTIONS",
	2: "SECRETS",
	3: "NAMESPACES",
}
var TaskKind_value = map[string]int32{
	"CONFIGS":    0,
	"ACTIONS":    1,
	"SECRETS":    2,
	"NAMESPACES": 3,
}

func (x TaskKind) String() string {
	return proto.EnumName(TaskKind_name, int32(x))
}
func (TaskKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type PayloadKind int32

const (
	PayloadKind_FILE   PayloadKind = 0
	PayloadKind_ENV    PayloadKind = 1
	PayloadKind_ACTION PayloadKind = 2
)

var PayloadKind_name = map[int32]string{
	0: "FILE",
	1: "ENV",
	2: "ACTION",
}
var PayloadKind_value = map[string]int32{
	"FILE":   0,
	"ENV":    1,
	"ACTION": 2,
}

func (x PayloadKind) String() string {
	return proto.EnumName(PayloadKind_name, int32(x))
}
func (PayloadKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type StrategyKind int32

const (
	StrategyKind_AT_ONCE        StrategyKind = 0
	StrategyKind_ROLLING_UPDATE StrategyKind = 1
)

var StrategyKind_name = map[int32]string{
	0: "AT_ONCE",
	1: "ROLLING_UPDATE",
}
var StrategyKind_value = map[string]int32{
	"AT_ONCE":        0,
	"ROLLING_UPDATE": 1,
}

func (x StrategyKind) String() string {
	return proto.EnumName(StrategyKind_name, int32(x))
}
func (StrategyKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type CompareKind int32

const (
	CompareKind_ALL CompareKind = 0
	CompareKind_ANY CompareKind = 1
)

var CompareKind_name = map[int32]string{
	0: "ALL",
	1: "ANY",
}
var CompareKind_value = map[string]int32{
	"ALL": 0,
	"ANY": 1,
}

func (x CompareKind) String() string {
	return proto.EnumName(CompareKind_name, int32(x))
}
func (CompareKind) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

// Request helper messages
type Strategy struct {
	Type StrategyKind `protobuf:"varint,1,opt,name=type,enum=blackhole.StrategyKind" json:"type,omitempty"`
	Kind string       `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
}

func (m *Strategy) Reset()                    { *m = Strategy{} }
func (m *Strategy) String() string            { return proto.CompactTextString(m) }
func (*Strategy) ProtoMessage()               {}
func (*Strategy) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Strategy) GetType() StrategyKind {
	if m != nil {
		return m.Type
	}
	return StrategyKind_AT_ONCE
}

func (m *Strategy) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

type Selector struct {
	Kind   CompareKind       `protobuf:"varint,1,opt,name=kind,enum=blackhole.CompareKind" json:"kind,omitempty"`
	Labels map[string]string `protobuf:"bytes,2,rep,name=labels" json:"labels,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Selector) Reset()                    { *m = Selector{} }
func (m *Selector) String() string            { return proto.CompactTextString(m) }
func (*Selector) ProtoMessage()               {}
func (*Selector) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Selector) GetKind() CompareKind {
	if m != nil {
		return m.Kind
	}
	return CompareKind_ALL
}

func (m *Selector) GetLabels() map[string]string {
	if m != nil {
		return m.Labels
	}
	return nil
}

type Payload struct {
	Kind  PayloadKind       `protobuf:"varint,1,opt,name=kind,enum=blackhole.PayloadKind" json:"kind,omitempty"`
	Value map[string]string `protobuf:"bytes,2,rep,name=value" json:"value,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *Payload) Reset()                    { *m = Payload{} }
func (m *Payload) String() string            { return proto.CompactTextString(m) }
func (*Payload) ProtoMessage()               {}
func (*Payload) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Payload) GetKind() PayloadKind {
	if m != nil {
		return m.Kind
	}
	return PayloadKind_FILE
}

func (m *Payload) GetValue() map[string]string {
	if m != nil {
		return m.Value
	}
	return nil
}

type Metadata struct {
	TaskName            string `protobuf:"bytes,1,opt,name=taskName" json:"taskName,omitempty"`
	Timestamp           int64  `protobuf:"varint,2,opt,name=timestamp" json:"timestamp,omitempty"`
	Namespace           string `protobuf:"bytes,3,opt,name=namespace" json:"namespace,omitempty"`
	ForceNamespaceQueue bool   `protobuf:"varint,4,opt,name=forceNamespaceQueue" json:"forceNamespaceQueue,omitempty"`
	Queue               string `protobuf:"bytes,5,opt,name=queue" json:"queue,omitempty"`
}

func (m *Metadata) Reset()                    { *m = Metadata{} }
func (m *Metadata) String() string            { return proto.CompactTextString(m) }
func (*Metadata) ProtoMessage()               {}
func (*Metadata) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *Metadata) GetTaskName() string {
	if m != nil {
		return m.TaskName
	}
	return ""
}

func (m *Metadata) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Metadata) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

func (m *Metadata) GetForceNamespaceQueue() bool {
	if m != nil {
		return m.ForceNamespaceQueue
	}
	return false
}

func (m *Metadata) GetQueue() string {
	if m != nil {
		return m.Queue
	}
	return ""
}

type PutTask struct {
	RegionId  string     `protobuf:"bytes,1,opt,name=region_id,json=regionId" json:"region_id,omitempty"`
	ClusterId string     `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId" json:"cluster_id,omitempty"`
	Strategy  *Strategy  `protobuf:"bytes,3,opt,name=strategy" json:"strategy,omitempty"`
	Selector  *Selector  `protobuf:"bytes,4,opt,name=selector" json:"selector,omitempty"`
	Payload   []*Payload `protobuf:"bytes,5,rep,name=payload" json:"payload,omitempty"`
}

func (m *PutTask) Reset()                    { *m = PutTask{} }
func (m *PutTask) String() string            { return proto.CompactTextString(m) }
func (*PutTask) ProtoMessage()               {}
func (*PutTask) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *PutTask) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *PutTask) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *PutTask) GetStrategy() *Strategy {
	if m != nil {
		return m.Strategy
	}
	return nil
}

func (m *PutTask) GetSelector() *Selector {
	if m != nil {
		return m.Selector
	}
	return nil
}

func (m *PutTask) GetPayload() []*Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

// Reques messages
type PutReq struct {
	Version string            `protobuf:"bytes,1,opt,name=version" json:"version,omitempty"`
	UserId  string            `protobuf:"bytes,2,opt,name=user_id,json=userId" json:"user_id,omitempty"`
	Kind    TaskKind          `protobuf:"varint,3,opt,name=kind,enum=blackhole.TaskKind" json:"kind,omitempty"`
	Mtdata  *Metadata         `protobuf:"bytes,4,opt,name=mtdata" json:"mtdata,omitempty"`
	Tasks   []*PutTask        `protobuf:"bytes,5,rep,name=tasks" json:"tasks,omitempty"`
	Extras  map[string]string `protobuf:"bytes,6,rep,name=extras" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
}

func (m *PutReq) Reset()                    { *m = PutReq{} }
func (m *PutReq) String() string            { return proto.CompactTextString(m) }
func (*PutReq) ProtoMessage()               {}
func (*PutReq) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *PutReq) GetVersion() string {
	if m != nil {
		return m.Version
	}
	return ""
}

func (m *PutReq) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

func (m *PutReq) GetKind() TaskKind {
	if m != nil {
		return m.Kind
	}
	return TaskKind_CONFIGS
}

func (m *PutReq) GetMtdata() *Metadata {
	if m != nil {
		return m.Mtdata
	}
	return nil
}

func (m *PutReq) GetTasks() []*PutTask {
	if m != nil {
		return m.Tasks
	}
	return nil
}

func (m *PutReq) GetExtras() map[string]string {
	if m != nil {
		return m.Extras
	}
	return nil
}

// Response message
type Resp struct {
	Msg string `protobuf:"bytes,1,opt,name=msg" json:"msg,omitempty"`
}

func (m *Resp) Reset()                    { *m = Resp{} }
func (m *Resp) String() string            { return proto.CompactTextString(m) }
func (*Resp) ProtoMessage()               {}
func (*Resp) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Resp) GetMsg() string {
	if m != nil {
		return m.Msg
	}
	return ""
}

func init() {
	proto.RegisterType((*Strategy)(nil), "blackhole.Strategy")
	proto.RegisterType((*Selector)(nil), "blackhole.Selector")
	proto.RegisterType((*Payload)(nil), "blackhole.Payload")
	proto.RegisterType((*Metadata)(nil), "blackhole.Metadata")
	proto.RegisterType((*PutTask)(nil), "blackhole.PutTask")
	proto.RegisterType((*PutReq)(nil), "blackhole.PutReq")
	proto.RegisterType((*Resp)(nil), "blackhole.Resp")
	proto.RegisterEnum("blackhole.TaskKind", TaskKind_name, TaskKind_value)
	proto.RegisterEnum("blackhole.PayloadKind", PayloadKind_name, PayloadKind_value)
	proto.RegisterEnum("blackhole.StrategyKind", StrategyKind_name, StrategyKind_value)
	proto.RegisterEnum("blackhole.CompareKind", CompareKind_name, CompareKind_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for BlackHoleService service

type BlackHoleServiceClient interface {
	Put(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*Resp, error)
}

type blackHoleServiceClient struct {
	cc *grpc.ClientConn
}

func NewBlackHoleServiceClient(cc *grpc.ClientConn) BlackHoleServiceClient {
	return &blackHoleServiceClient{cc}
}

func (c *blackHoleServiceClient) Put(ctx context.Context, in *PutReq, opts ...grpc.CallOption) (*Resp, error) {
	out := new(Resp)
	err := grpc.Invoke(ctx, "/blackhole.BlackHoleService/Put", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// Server API for BlackHoleService service

type BlackHoleServiceServer interface {
	Put(context.Context, *PutReq) (*Resp, error)
}

func RegisterBlackHoleServiceServer(s *grpc.Server, srv BlackHoleServiceServer) {
	s.RegisterService(&_BlackHoleService_serviceDesc, srv)
}

func _BlackHoleService_Put_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PutReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(BlackHoleServiceServer).Put(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/blackhole.BlackHoleService/Put",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(BlackHoleServiceServer).Put(ctx, req.(*PutReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _BlackHoleService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "blackhole.BlackHoleService",
	HandlerType: (*BlackHoleServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Put",
			Handler:    _BlackHoleService_Put_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "blackhole/blackhole.proto",
}

func init() { proto.RegisterFile("blackhole/blackhole.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 725 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x54, 0xdd, 0x6e, 0xda, 0x4c,
	0x10, 0x8d, 0x31, 0x18, 0x18, 0x3e, 0xe5, 0x73, 0x37, 0x55, 0xe3, 0xd2, 0x46, 0x41, 0xdc, 0x14,
	0x91, 0x08, 0x5a, 0xa2, 0xaa, 0x69, 0x6f, 0x2a, 0x42, 0x9d, 0x14, 0x85, 0x18, 0x6a, 0xd3, 0x48,
	0xed, 0x4d, 0xb4, 0xd8, 0x5b, 0x62, 0x61, 0x63, 0xe2, 0x5d, 0x47, 0xe5, 0x7d, 0x7a, 0x55, 0xa9,
	0x8f, 0xd3, 0xf7, 0xa9, 0x76, 0x6d, 0x83, 0x55, 0x50, 0xa5, 0xdc, 0xed, 0x9c, 0x39, 0x33, 0x7b,
	0xe6, 0x67, 0x17, 0x9e, 0x4e, 0x3c, 0x6c, 0xcf, 0x6e, 0x03, 0x8f, 0xb4, 0x57, 0xa7, 0xd6, 0x22,
	0x0c, 0x58, 0x80, 0xca, 0x2b, 0xa0, 0x7e, 0x09, 0x25, 0x8b, 0x85, 0x98, 0x91, 0xe9, 0x12, 0x1d,
	0x41, 0x9e, 0x2d, 0x17, 0x44, 0x93, 0x6a, 0x52, 0x63, 0xb7, 0xb3, 0xdf, 0x5a, 0x87, 0xa5, 0x94,
	0x4b, 0x77, 0xee, 0x98, 0x82, 0x84, 0x10, 0xe4, 0x67, 0xee, 0xdc, 0xd1, 0x72, 0x35, 0xa9, 0x51,
	0x36, 0xc5, 0xb9, 0xfe, 0x53, 0x82, 0x92, 0x45, 0x3c, 0x62, 0xb3, 0x20, 0x44, 0xcd, 0x84, 0x10,
	0x67, 0x7b, 0x92, 0xc9, 0xd6, 0x0b, 0xfc, 0x05, 0x0e, 0x49, 0x9c, 0x8c, 0x73, 0xd0, 0x1b, 0x50,
	0x3c, 0x3c, 0x21, 0x1e, 0xd5, 0x72, 0x35, 0xb9, 0x51, 0xe9, 0x1c, 0x66, 0xef, 0x4e, 0x12, 0xb6,
	0x06, 0x82, 0xa1, 0xcf, 0x59, 0xb8, 0x34, 0x13, 0x7a, 0xf5, 0x2d, 0x54, 0x32, 0x30, 0x52, 0x41,
	0x9e, 0x91, 0xa5, 0xb8, 0xb2, 0x6c, 0xf2, 0x23, 0x7a, 0x0c, 0x85, 0x7b, 0xec, 0x45, 0x24, 0xd1,
	0x19, 0x1b, 0xef, 0x72, 0xa7, 0x52, 0xfd, 0x87, 0x04, 0xc5, 0x11, 0x5e, 0x7a, 0x01, 0x76, 0xfe,
	0xa1, 0x35, 0x61, 0x64, 0xb4, 0x9e, 0xac, 0x33, 0x72, 0xa9, 0x07, 0x9b, 0xe4, 0xd6, 0x35, 0xf7,
	0xc7, 0x42, 0x63, 0x6e, 0xf5, 0x14, 0x60, 0x0d, 0x3e, 0x48, 0x26, 0xef, 0xe9, 0x15, 0x61, 0xd8,
	0xc1, 0x0c, 0xa3, 0x2a, 0x94, 0x18, 0xa6, 0x33, 0x03, 0xfb, 0x24, 0x89, 0x5e, 0xd9, 0xe8, 0x39,
	0x94, 0x99, 0xeb, 0x13, 0xca, 0xb0, 0xbf, 0x10, 0x69, 0x64, 0x73, 0x0d, 0x70, 0xef, 0x1c, 0xfb,
	0x84, 0x2e, 0xb0, 0x4d, 0x34, 0x59, 0x84, 0xae, 0x01, 0xf4, 0x12, 0xf6, 0xbe, 0x05, 0xa1, 0x4d,
	0x8c, 0x14, 0xf9, 0x14, 0x91, 0x88, 0x68, 0xf9, 0x9a, 0xd4, 0x28, 0x99, 0xdb, 0x5c, 0x5c, 0xf0,
	0x9d, 0xe0, 0x14, 0x62, 0xc1, 0xc2, 0xa8, 0xff, 0xe6, 0x3d, 0x8d, 0xd8, 0x18, 0xd3, 0x19, 0x7a,
	0x06, 0xe5, 0x90, 0x4c, 0xdd, 0x60, 0x7e, 0xe3, 0x3a, 0xa9, 0xd8, 0x18, 0xe8, 0x3b, 0xe8, 0x00,
	0xc0, 0xf6, 0x22, 0xca, 0x48, 0xc8, 0xbd, 0x71, 0xd1, 0xe5, 0x04, 0xe9, 0x3b, 0xa8, 0x0d, 0x25,
	0x9a, 0xac, 0x9c, 0x10, 0x5b, 0xe9, 0xec, 0x6d, 0xd9, 0x46, 0x73, 0x45, 0x12, 0x01, 0xc9, 0x9e,
	0x08, 0xd5, 0x7f, 0x05, 0x24, 0x2e, 0x73, 0x45, 0x42, 0xc7, 0x50, 0x5c, 0xc4, 0xd3, 0xd2, 0x0a,
	0x62, 0x8e, 0x68, 0x73, 0x8e, 0x66, 0x4a, 0xa9, 0xff, 0xca, 0x81, 0x32, 0x8a, 0x98, 0x49, 0xee,
	0x90, 0x06, 0xc5, 0x7b, 0x12, 0x52, 0x37, 0x98, 0x27, 0x45, 0xa5, 0x26, 0xda, 0x87, 0x62, 0x44,
	0xb3, 0x05, 0x29, 0xdc, 0xec, 0x3b, 0xe8, 0x45, 0xb2, 0x5d, 0xb2, 0xd8, 0xae, 0xac, 0x30, 0xde,
	0xa8, 0xcc, 0x6a, 0x1d, 0x81, 0xe2, 0x33, 0x3e, 0xe8, 0x2d, 0x35, 0xa4, 0x3b, 0x60, 0x26, 0x14,
	0xd4, 0x80, 0x02, 0x9f, 0x3d, 0xdd, 0xa6, 0x3f, 0x1e, 0x81, 0x19, 0x13, 0xd0, 0x6b, 0x50, 0xc8,
	0x77, 0x16, 0x62, 0xaa, 0x29, 0x9b, 0x2b, 0x2b, 0xaa, 0x6a, 0xe9, 0xc2, 0x9f, 0xbc, 0xad, 0x98,
	0xcc, 0xdf, 0x56, 0x06, 0x7e, 0xd0, 0xd2, 0x6a, 0x90, 0x37, 0x09, 0x5d, 0xf0, 0x18, 0x9f, 0x4e,
	0xd3, 0x18, 0x9f, 0x4e, 0x9b, 0x5d, 0x28, 0xa5, 0x45, 0xa3, 0x0a, 0x14, 0x7b, 0x43, 0xe3, 0xbc,
	0x7f, 0x61, 0xa9, 0x3b, 0xdc, 0xe8, 0xf6, 0xc6, 0xfd, 0xa1, 0x61, 0xa9, 0x12, 0x37, 0x2c, 0xbd,
	0x67, 0xea, 0x63, 0x4b, 0xcd, 0xa1, 0x5d, 0x00, 0xa3, 0x7b, 0xa5, 0x5b, 0xa3, 0x6e, 0x4f, 0xb7,
	0x54, 0xb9, 0x79, 0x0c, 0x95, 0xcc, 0xab, 0x44, 0x25, 0xc8, 0x9f, 0xf7, 0x07, 0xba, 0xba, 0x83,
	0x8a, 0x20, 0xeb, 0xc6, 0xb5, 0x2a, 0x21, 0x00, 0x25, 0xce, 0xa5, 0xe6, 0x9a, 0x6d, 0xf8, 0x2f,
	0xfb, 0x7b, 0x89, 0x7b, 0xc6, 0x37, 0x43, 0xa3, 0xc7, 0x23, 0x10, 0xec, 0x9a, 0xc3, 0xc1, 0xa0,
	0x6f, 0x5c, 0xdc, 0x7c, 0x1e, 0x7d, 0xe8, 0x8e, 0x75, 0x55, 0x6a, 0x1e, 0x42, 0x25, 0xf3, 0x41,
	0xf1, 0xa4, 0xdd, 0xc1, 0x20, 0xce, 0xde, 0x35, 0xbe, 0xa8, 0x52, 0xe7, 0x3d, 0xa8, 0x67, 0xbc,
	0x7f, 0x1f, 0x03, 0x8f, 0x58, 0x24, 0xbc, 0x77, 0x6d, 0x82, 0x8e, 0x40, 0x1e, 0x45, 0x0c, 0x3d,
	0xda, 0xe8, 0x6c, 0xf5, 0xff, 0x0c, 0xc4, 0x7b, 0x52, 0xdf, 0x39, 0xab, 0x7f, 0xad, 0x4d, 0x5d,
	0x76, 0x1b, 0x4d, 0x5a, 0x76, 0xe0, 0xb7, 0xed, 0x57, 0x1d, 0xda, 0xa6, 0xf6, 0x2d, 0xf1, 0x33,
	0x1f, 0xf5, 0x44, 0x11, 0x3f, 0xf5, 0xc9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x77, 0xc3, 0x8c,
	0x9f, 0xc6, 0x05, 0x00, 0x00,
}
