// Code generated by protoc-gen-go. DO NOT EDIT.
// source: flusher/flusher.proto

/*
Package flusher is a generated protocol buffer package.

It is generated from these files:
	flusher/flusher.proto

It has these top-level messages:
	Event
	Update
	Error
*/
package flusher

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import blackhole "github.com/c12s/scheme/blackhole"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Event struct {
	TaskKey string               `protobuf:"bytes,1,opt,name=taskKey" json:"taskKey,omitempty"`
	Kind    string               `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Payload []*blackhole.Payload `protobuf:"bytes,3,rep,name=payload" json:"payload,omitempty"`
}

func (m *Event) Reset()                    { *m = Event{} }
func (m *Event) String() string            { return proto.CompactTextString(m) }
func (*Event) ProtoMessage()               {}
func (*Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *Event) GetTaskKey() string {
	if m != nil {
		return m.TaskKey
	}
	return ""
}

func (m *Event) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Event) GetPayload() []*blackhole.Payload {
	if m != nil {
		return m.Payload
	}
	return nil
}

type Update struct {
	TaskKey string `protobuf:"bytes,1,opt,name=taskKey" json:"taskKey,omitempty"`
	Kind    string `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Node    string `protobuf:"bytes,3,opt,name=node" json:"node,omitempty"`
}

func (m *Update) Reset()                    { *m = Update{} }
func (m *Update) String() string            { return proto.CompactTextString(m) }
func (*Update) ProtoMessage()               {}
func (*Update) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *Update) GetTaskKey() string {
	if m != nil {
		return m.TaskKey
	}
	return ""
}

func (m *Update) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Update) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

type Error struct {
	TaskKey   string `protobuf:"bytes,1,opt,name=taskKey" json:"taskKey,omitempty"`
	Kind      string `protobuf:"bytes,2,opt,name=kind" json:"kind,omitempty"`
	Node      string `protobuf:"bytes,3,opt,name=node" json:"node,omitempty"`
	Message   string `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	Timestamp int64  `protobuf:"varint,5,opt,name=timestamp" json:"timestamp,omitempty"`
	Level     string `protobuf:"bytes,6,opt,name=level" json:"level,omitempty"`
}

func (m *Error) Reset()                    { *m = Error{} }
func (m *Error) String() string            { return proto.CompactTextString(m) }
func (*Error) ProtoMessage()               {}
func (*Error) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *Error) GetTaskKey() string {
	if m != nil {
		return m.TaskKey
	}
	return ""
}

func (m *Error) GetKind() string {
	if m != nil {
		return m.Kind
	}
	return ""
}

func (m *Error) GetNode() string {
	if m != nil {
		return m.Node
	}
	return ""
}

func (m *Error) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *Error) GetTimestamp() int64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *Error) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func init() {
	proto.RegisterType((*Event)(nil), "flusher.Event")
	proto.RegisterType((*Update)(nil), "flusher.Update")
	proto.RegisterType((*Error)(nil), "flusher.Error")
}

func init() { proto.RegisterFile("flusher/flusher.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 249 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x91, 0xcd, 0x4a, 0xf4, 0x30,
	0x14, 0x86, 0xe9, 0xd7, 0x3f, 0xe6, 0x7c, 0xbb, 0x83, 0x42, 0x14, 0x91, 0xd2, 0x55, 0x17, 0xd2,
	0xe2, 0x78, 0x07, 0xc2, 0x6c, 0x74, 0x23, 0x05, 0x37, 0xee, 0xd2, 0xf4, 0x38, 0x2d, 0x4d, 0x9a,
	0x92, 0x64, 0x06, 0xe6, 0x4a, 0xbc, 0x5d, 0x99, 0xa6, 0x75, 0xd6, 0xe2, 0x2a, 0xef, 0xf3, 0xe6,
	0xe4, 0x09, 0x24, 0x70, 0xfd, 0x29, 0x0f, 0xb6, 0x23, 0x53, 0x2d, 0x6b, 0x39, 0x19, 0xed, 0x34,
	0xa6, 0x0b, 0xde, 0xde, 0x34, 0x92, 0x8b, 0xa1, 0xd3, 0x92, 0xaa, 0x9f, 0xe4, 0x67, 0x72, 0x01,
	0xf1, 0xee, 0x48, 0xa3, 0x43, 0x06, 0xa9, 0xe3, 0x76, 0x78, 0xa5, 0x13, 0x0b, 0xb2, 0xa0, 0xd8,
	0xd4, 0x2b, 0x22, 0x42, 0x34, 0xf4, 0x63, 0xcb, 0xfe, 0xcd, 0xf5, 0x9c, 0xf1, 0x01, 0xd2, 0x89,
	0x9f, 0xa4, 0xe6, 0x2d, 0x0b, 0xb3, 0xb0, 0xf8, 0xbf, 0xc5, 0xf2, 0x62, 0x7e, 0xf3, 0x3b, 0xf5,
	0x3a, 0x92, 0xbf, 0x40, 0xf2, 0x3e, 0xb5, 0xdc, 0xd1, 0x2f, 0x6f, 0x41, 0x88, 0x46, 0xdd, 0x12,
	0x0b, 0x7d, 0x77, 0xce, 0xf9, 0x57, 0x00, 0xf1, 0xce, 0x18, 0x6d, 0xfe, 0xee, 0x3a, 0x1b, 0x14,
	0x59, 0xcb, 0xf7, 0xc4, 0x22, 0x6f, 0x58, 0x10, 0xef, 0x60, 0xe3, 0x7a, 0x45, 0xd6, 0x71, 0x35,
	0xb1, 0x38, 0x0b, 0x8a, 0xb0, 0xbe, 0x14, 0x78, 0x05, 0xb1, 0xa4, 0x23, 0x49, 0x96, 0xcc, 0xa7,
	0x3c, 0x3c, 0x67, 0x1f, 0xf7, 0xfb, 0xde, 0x75, 0x87, 0xa6, 0x14, 0x5a, 0x55, 0xe2, 0x71, 0x6b,
	0x2b, 0x2b, 0x3a, 0x52, 0xb4, 0x7e, 0x4b, 0x93, 0xcc, 0x6f, 0xfe, 0xf4, 0x1d, 0x00, 0x00, 0xff,
	0xff, 0xa2, 0xf5, 0x4d, 0xe0, 0xb0, 0x01, 0x00, 0x00,
}
