// Code generated by protoc-gen-go. DO NOT EDIT.
// source: celestial/celestial.proto

package celestial

import (
	context "context"
	fmt "fmt"
	core "github.com/c12s/scheme/core"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

//Enumerations
type ReqKind int32

const (
	ReqKind_SECRETS    ReqKind = 0
	ReqKind_CONFIGS    ReqKind = 1
	ReqKind_ACTIONS    ReqKind = 2
	ReqKind_NAMESPACES ReqKind = 3
	ReqKind_ROLES      ReqKind = 4
	ReqKind_TOPOLOGY   ReqKind = 5
)

var ReqKind_name = map[int32]string{
	0: "SECRETS",
	1: "CONFIGS",
	2: "ACTIONS",
	3: "NAMESPACES",
	4: "ROLES",
	5: "TOPOLOGY",
}

var ReqKind_value = map[string]int32{
	"SECRETS":    0,
	"CONFIGS":    1,
	"ACTIONS":    2,
	"NAMESPACES": 3,
	"ROLES":      4,
	"TOPOLOGY":   5,
}

func (x ReqKind) String() string {
	return proto.EnumName(ReqKind_name, int32(x))
}

func (ReqKind) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_cba9184bd420c558, []int{0}
}

// List messages
type ListReq struct {
	Kind                 ReqKind           `protobuf:"varint,1,opt,name=kind,proto3,enum=celestial.ReqKind" json:"kind,omitempty"`
	Extras               map[string]string `protobuf:"bytes,2,rep,name=extras,proto3" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListReq) Reset()         { *m = ListReq{} }
func (m *ListReq) String() string { return proto.CompactTextString(m) }
func (*ListReq) ProtoMessage()    {}
func (*ListReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba9184bd420c558, []int{0}
}

func (m *ListReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListReq.Unmarshal(m, b)
}
func (m *ListReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListReq.Marshal(b, m, deterministic)
}
func (m *ListReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListReq.Merge(m, src)
}
func (m *ListReq) XXX_Size() int {
	return xxx_messageInfo_ListReq.Size(m)
}
func (m *ListReq) XXX_DiscardUnknown() {
	xxx_messageInfo_ListReq.DiscardUnknown(m)
}

var xxx_messageInfo_ListReq proto.InternalMessageInfo

func (m *ListReq) GetKind() ReqKind {
	if m != nil {
		return m.Kind
	}
	return ReqKind_SECRETS
}

func (m *ListReq) GetExtras() map[string]string {
	if m != nil {
		return m.Extras
	}
	return nil
}

type Data struct {
	Data                 map[string]string `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba9184bd420c558, []int{1}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetData() map[string]string {
	if m != nil {
		return m.Data
	}
	return nil
}

type ListResp struct {
	RegionId             string            `protobuf:"bytes,1,opt,name=region_id,json=regionId,proto3" json:"region_id,omitempty"`
	ClusterId            string            `protobuf:"bytes,2,opt,name=cluster_id,json=clusterId,proto3" json:"cluster_id,omitempty"`
	NodeId               string            `protobuf:"bytes,3,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Data                 []*Data           `protobuf:"bytes,4,rep,name=data,proto3" json:"data,omitempty"`
	Extras               map[string]string `protobuf:"bytes,5,rep,name=extras,proto3" json:"extras,omitempty" protobuf_key:"bytes,1,opt,name=key,proto3" protobuf_val:"bytes,2,opt,name=value,proto3"`
	Error                string            `protobuf:"bytes,6,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}          `json:"-"`
	XXX_unrecognized     []byte            `json:"-"`
	XXX_sizecache        int32             `json:"-"`
}

func (m *ListResp) Reset()         { *m = ListResp{} }
func (m *ListResp) String() string { return proto.CompactTextString(m) }
func (*ListResp) ProtoMessage()    {}
func (*ListResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba9184bd420c558, []int{2}
}

func (m *ListResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ListResp.Unmarshal(m, b)
}
func (m *ListResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ListResp.Marshal(b, m, deterministic)
}
func (m *ListResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ListResp.Merge(m, src)
}
func (m *ListResp) XXX_Size() int {
	return xxx_messageInfo_ListResp.Size(m)
}
func (m *ListResp) XXX_DiscardUnknown() {
	xxx_messageInfo_ListResp.DiscardUnknown(m)
}

var xxx_messageInfo_ListResp proto.InternalMessageInfo

func (m *ListResp) GetRegionId() string {
	if m != nil {
		return m.RegionId
	}
	return ""
}

func (m *ListResp) GetClusterId() string {
	if m != nil {
		return m.ClusterId
	}
	return ""
}

func (m *ListResp) GetNodeId() string {
	if m != nil {
		return m.NodeId
	}
	return ""
}

func (m *ListResp) GetData() []*Data {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *ListResp) GetExtras() map[string]string {
	if m != nil {
		return m.Extras
	}
	return nil
}

func (m *ListResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

type MutateReq struct {
	Mutate               *core.Task `protobuf:"bytes,1,opt,name=mutate,proto3" json:"mutate,omitempty"`
	Index                []string   `protobuf:"bytes,2,rep,name=index,proto3" json:"index,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *MutateReq) Reset()         { *m = MutateReq{} }
func (m *MutateReq) String() string { return proto.CompactTextString(m) }
func (*MutateReq) ProtoMessage()    {}
func (*MutateReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba9184bd420c558, []int{3}
}

func (m *MutateReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateReq.Unmarshal(m, b)
}
func (m *MutateReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateReq.Marshal(b, m, deterministic)
}
func (m *MutateReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateReq.Merge(m, src)
}
func (m *MutateReq) XXX_Size() int {
	return xxx_messageInfo_MutateReq.Size(m)
}
func (m *MutateReq) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateReq.DiscardUnknown(m)
}

var xxx_messageInfo_MutateReq proto.InternalMessageInfo

func (m *MutateReq) GetMutate() *core.Task {
	if m != nil {
		return m.Mutate
	}
	return nil
}

func (m *MutateReq) GetIndex() []string {
	if m != nil {
		return m.Index
	}
	return nil
}

// Mutate messages
type MutateResp struct {
	Error                string   `protobuf:"bytes,1,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MutateResp) Reset()         { *m = MutateResp{} }
func (m *MutateResp) String() string { return proto.CompactTextString(m) }
func (*MutateResp) ProtoMessage()    {}
func (*MutateResp) Descriptor() ([]byte, []int) {
	return fileDescriptor_cba9184bd420c558, []int{4}
}

func (m *MutateResp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MutateResp.Unmarshal(m, b)
}
func (m *MutateResp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MutateResp.Marshal(b, m, deterministic)
}
func (m *MutateResp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MutateResp.Merge(m, src)
}
func (m *MutateResp) XXX_Size() int {
	return xxx_messageInfo_MutateResp.Size(m)
}
func (m *MutateResp) XXX_DiscardUnknown() {
	xxx_messageInfo_MutateResp.DiscardUnknown(m)
}

var xxx_messageInfo_MutateResp proto.InternalMessageInfo

func (m *MutateResp) GetError() string {
	if m != nil {
		return m.Error
	}
	return ""
}

func init() {
	proto.RegisterEnum("celestial.ReqKind", ReqKind_name, ReqKind_value)
	proto.RegisterType((*ListReq)(nil), "celestial.ListReq")
	proto.RegisterMapType((map[string]string)(nil), "celestial.ListReq.ExtrasEntry")
	proto.RegisterType((*Data)(nil), "celestial.Data")
	proto.RegisterMapType((map[string]string)(nil), "celestial.Data.DataEntry")
	proto.RegisterType((*ListResp)(nil), "celestial.ListResp")
	proto.RegisterMapType((map[string]string)(nil), "celestial.ListResp.ExtrasEntry")
	proto.RegisterType((*MutateReq)(nil), "celestial.MutateReq")
	proto.RegisterType((*MutateResp)(nil), "celestial.MutateResp")
}

func init() {
	proto.RegisterFile("celestial/celestial.proto", fileDescriptor_cba9184bd420c558)
}

var fileDescriptor_cba9184bd420c558 = []byte{
	// 513 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0x4f, 0x6f, 0xd3, 0x4e,
	0x10, 0xad, 0x13, 0xe7, 0x8f, 0x27, 0x3f, 0xb5, 0xd6, 0xfc, 0x40, 0xb8, 0x46, 0x40, 0x64, 0x24,
	0x54, 0x21, 0xe1, 0xa8, 0x46, 0xa2, 0xc0, 0x2d, 0x18, 0x53, 0x59, 0x24, 0x71, 0x65, 0xe7, 0x52,
	0x2e, 0xc8, 0xb5, 0x57, 0xad, 0x95, 0xc4, 0x4e, 0x77, 0x37, 0x55, 0x7b, 0xe1, 0x23, 0xf0, 0x29,
	0xf8, 0xa0, 0x68, 0xd7, 0xae, 0x63, 0xd1, 0x5c, 0x10, 0x97, 0xd5, 0xce, 0x7b, 0xb3, 0x33, 0xfb,
	0xde, 0xce, 0xc2, 0x61, 0x42, 0x96, 0x84, 0xf1, 0x2c, 0x5e, 0x8e, 0xea, 0x9d, 0xbd, 0xa6, 0x05,
	0x2f, 0x50, 0xab, 0x01, 0xf3, 0x20, 0x29, 0x28, 0x19, 0x89, 0xa5, 0xe4, 0xac, 0x5f, 0x0a, 0xf4,
	0x26, 0x19, 0xe3, 0x21, 0xb9, 0xc6, 0x57, 0xa0, 0x2e, 0xb2, 0x3c, 0x35, 0x94, 0xa1, 0x72, 0xb4,
	0xef, 0xa0, 0xbd, 0xad, 0x13, 0x92, 0xeb, 0xaf, 0x59, 0x9e, 0x86, 0x92, 0xc7, 0x77, 0xd0, 0x25,
	0xb7, 0x9c, 0xc6, 0xcc, 0x68, 0x0d, 0xdb, 0x47, 0x03, 0xe7, 0x79, 0x23, 0xb3, 0xaa, 0x65, 0x7b,
	0x32, 0xc1, 0xcb, 0x39, 0xbd, 0x0b, 0xab, 0x6c, 0xf3, 0x03, 0x0c, 0x1a, 0x30, 0xea, 0xd0, 0x5e,
	0x90, 0x3b, 0xd9, 0x4d, 0x0b, 0xc5, 0x16, 0x1f, 0x41, 0xe7, 0x26, 0x5e, 0x6e, 0x88, 0xd1, 0x92,
	0x58, 0x19, 0x7c, 0x6c, 0xbd, 0x57, 0xac, 0x1c, 0xd4, 0xcf, 0x31, 0x8f, 0xf1, 0x0d, 0xa8, 0x69,
	0xcc, 0x63, 0x43, 0x91, 0x8d, 0x0f, 0x1b, 0x8d, 0x05, 0x2d, 0x97, 0xb2, 0xa7, 0x4c, 0x33, 0x4f,
	0x40, 0xab, 0xa1, 0xbf, 0xea, 0xf7, 0xb3, 0x05, 0xfd, 0x52, 0x0a, 0x5b, 0xe3, 0x53, 0xd0, 0x28,
	0xb9, 0xcc, 0x8a, 0xfc, 0x7b, 0x96, 0x56, 0xc7, 0xfb, 0x25, 0xe0, 0xa7, 0xf8, 0x0c, 0x20, 0x59,
	0x6e, 0x18, 0x27, 0x54, 0xb0, 0x65, 0x21, 0xad, 0x42, 0xfc, 0x14, 0x9f, 0x40, 0x2f, 0x2f, 0x52,
	0x22, 0xb8, 0xb6, 0xe4, 0xba, 0x22, 0xf4, 0x53, 0x7c, 0x59, 0x29, 0x51, 0xa5, 0x92, 0x83, 0x3f,
	0x94, 0x94, 0xf7, 0xc7, 0x93, 0xda, 0xe9, 0x8e, 0x4c, 0x7b, 0xf1, 0xc0, 0x69, 0xb6, 0xde, 0x65,
	0xb5, 0x50, 0x46, 0x28, 0x2d, 0xa8, 0xd1, 0x2d, 0x95, 0xc9, 0xe0, 0x5f, 0x1e, 0xc0, 0x03, 0x6d,
	0xba, 0xe1, 0x31, 0x27, 0x62, 0x50, 0x2c, 0xe8, 0xae, 0x64, 0x20, 0xcf, 0x0e, 0x1c, 0xb0, 0xe5,
	0x44, 0xcd, 0x63, 0xb6, 0x08, 0x2b, 0x46, 0x94, 0xca, 0xf2, 0x94, 0xdc, 0xca, 0x19, 0xd1, 0xc2,
	0x32, 0xb0, 0x2c, 0x80, 0xfb, 0x32, 0x6c, 0xbd, 0xbd, 0xa5, 0xd2, 0xb8, 0xe5, 0xeb, 0x73, 0xe8,
	0x55, 0xf3, 0x86, 0x03, 0xe8, 0x45, 0x9e, 0x1b, 0x7a, 0xf3, 0x48, 0xdf, 0x13, 0x81, 0x1b, 0xcc,
	0xbe, 0xf8, 0xa7, 0x91, 0xae, 0x88, 0x60, 0xec, 0xce, 0xfd, 0x60, 0x16, 0xe9, 0x2d, 0xdc, 0x07,
	0x98, 0x8d, 0xa7, 0x5e, 0x74, 0x36, 0x76, 0xbd, 0x48, 0x6f, 0xa3, 0x06, 0x9d, 0x30, 0x98, 0x78,
	0x91, 0xae, 0xe2, 0x7f, 0xd0, 0x9f, 0x07, 0x67, 0xc1, 0x24, 0x38, 0x3d, 0xd7, 0x3b, 0xce, 0x0f,
	0xd0, 0xdd, 0x7b, 0x03, 0x23, 0x42, 0x6f, 0xb2, 0x84, 0xe0, 0x31, 0xa8, 0xc2, 0x4a, 0xc4, 0x87,
	0x53, 0x6c, 0xfe, 0xbf, 0xc3, 0x6f, 0x6b, 0x4f, 0x3c, 0xcb, 0xb4, 0x52, 0xd9, 0x48, 0xa8, 0xfd,
	0x31, 0x1f, 0xef, 0x40, 0xc5, 0xc1, 0x4f, 0xd6, 0xb7, 0xe1, 0x65, 0xc6, 0xaf, 0x36, 0x17, 0x76,
	0x52, 0xac, 0x46, 0xc9, 0xb1, 0xc3, 0x46, 0x2c, 0xb9, 0x22, 0x2b, 0xb2, 0xfd, 0xb3, 0x17, 0x5d,
	0xf9, 0x31, 0xdf, 0xfe, 0x0e, 0x00, 0x00, 0xff, 0xff, 0x26, 0x40, 0x33, 0x90, 0xd1, 0x03, 0x00,
	0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CelestialServiceClient is the client API for CelestialService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CelestialServiceClient interface {
	List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error)
	Mutate(ctx context.Context, in *MutateReq, opts ...grpc.CallOption) (*MutateResp, error)
}

type celestialServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewCelestialServiceClient(cc grpc.ClientConnInterface) CelestialServiceClient {
	return &celestialServiceClient{cc}
}

func (c *celestialServiceClient) List(ctx context.Context, in *ListReq, opts ...grpc.CallOption) (*ListResp, error) {
	out := new(ListResp)
	err := c.cc.Invoke(ctx, "/celestial.CelestialService/List", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *celestialServiceClient) Mutate(ctx context.Context, in *MutateReq, opts ...grpc.CallOption) (*MutateResp, error) {
	out := new(MutateResp)
	err := c.cc.Invoke(ctx, "/celestial.CelestialService/Mutate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CelestialServiceServer is the server API for CelestialService service.
type CelestialServiceServer interface {
	List(context.Context, *ListReq) (*ListResp, error)
	Mutate(context.Context, *MutateReq) (*MutateResp, error)
}

// UnimplementedCelestialServiceServer can be embedded to have forward compatible implementations.
type UnimplementedCelestialServiceServer struct {
}

func (*UnimplementedCelestialServiceServer) List(ctx context.Context, req *ListReq) (*ListResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method List not implemented")
}
func (*UnimplementedCelestialServiceServer) Mutate(ctx context.Context, req *MutateReq) (*MutateResp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Mutate not implemented")
}

func RegisterCelestialServiceServer(s *grpc.Server, srv CelestialServiceServer) {
	s.RegisterService(&_CelestialService_serviceDesc, srv)
}

func _CelestialService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelestialServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celestial.CelestialService/List",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelestialServiceServer).List(ctx, req.(*ListReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _CelestialService_Mutate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MutateReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CelestialServiceServer).Mutate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/celestial.CelestialService/Mutate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CelestialServiceServer).Mutate(ctx, req.(*MutateReq))
	}
	return interceptor(ctx, in, info, handler)
}

var _CelestialService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "celestial.CelestialService",
	HandlerType: (*CelestialServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "List",
			Handler:    _CelestialService_List_Handler,
		},
		{
			MethodName: "Mutate",
			Handler:    _CelestialService_Mutate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "celestial/celestial.proto",
}
